-- ===========================================================
-- FINPILOT AUTH SERVICE SCHEMA (PostgreSQL)
-- Plain, portable SQL. No psql meta-commands.
-- Run this connected to the microfin_auth database.
-- Idempotent: safe to re-run.
-- ===========================================================

-- ===========================================
-- USERS
-- ===========================================
CREATE TABLE IF NOT EXISTS users (
    id                       BIGSERIAL PRIMARY KEY,
    username                 VARCHAR(100) UNIQUE NOT NULL,
    email                    VARCHAR(255) UNIQUE NOT NULL,
    password                 VARCHAR(255) NOT NULL,
    first_name               VARCHAR(100),
    last_name                VARCHAR(100),
    provider                 VARCHAR(50)  NOT NULL DEFAULT 'LOCAL', -- LOCAL, GOOGLE, GITHUB
    provider_id              VARCHAR(255),
    enabled                  BOOLEAN DEFAULT TRUE,
    account_non_locked       BOOLEAN DEFAULT TRUE,
    account_non_expired      BOOLEAN DEFAULT TRUE,
    credentials_non_expired  BOOLEAN DEFAULT TRUE,
    created_at               TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at               TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- ===========================================
-- ROLES
-- ===========================================
CREATE TABLE IF NOT EXISTS roles (
    id        BIGSERIAL PRIMARY KEY,
    role_name VARCHAR(50) UNIQUE NOT NULL
);

INSERT INTO roles (role_name) VALUES ('ROLE_USER')
ON CONFLICT (role_name) DO NOTHING;

INSERT INTO roles (role_name) VALUES ('ROLE_ADMIN')
ON CONFLICT (role_name) DO NOTHING;

-- ===========================================
-- USER ROLES
-- ===========================================
CREATE TABLE IF NOT EXISTS user_roles (
    user_id BIGINT NOT NULL,
    role_id BIGINT NOT NULL,
    PRIMARY KEY (user_id, role_id),
    CONSTRAINT fk_user_roles_user
        FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT fk_user_roles_role
        FOREIGN KEY (role_id) REFERENCES roles(id) ON DELETE CASCADE
);

-- ===========================================
-- REFRESH TOKENS
-- ===========================================
CREATE TABLE IF NOT EXISTS refresh_tokens (
    id          BIGSERIAL PRIMARY KEY,
    token       VARCHAR(500) UNIQUE NOT NULL,
    user_id     BIGINT NOT NULL,
    issued_at   TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    expiry_date TIMESTAMP NOT NULL,
    revoked     BOOLEAN DEFAULT FALSE,
    CONSTRAINT fk_refresh_tokens_user
        FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

-- ===========================================
-- PASSWORD RESET TOKENS
-- ===========================================
CREATE TABLE IF NOT EXISTS password_reset_tokens (
    id          BIGSERIAL PRIMARY KEY,
    token       VARCHAR(500) UNIQUE NOT NULL,
    user_id     BIGINT NOT NULL,
    expiry_date TIMESTAMP NOT NULL,
    used        BOOLEAN DEFAULT FALSE,
    CONSTRAINT fk_password_reset_user
        FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

-- ===========================================
-- LOGIN AUDIT
-- ===========================================
CREATE TABLE IF NOT EXISTS login_audit (
    id           BIGSERIAL PRIMARY KEY,
    user_id      BIGINT,
    username     VARCHAR(100),
    ip_address   VARCHAR(100),
    login_status VARCHAR(20), -- SUCCESS / FAILED
    login_time   TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_login_audit_user
        FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL
);

-- ===========================================
-- INDEXES
-- ===========================================
CREATE INDEX IF NOT EXISTS idx_users_username          ON users(username);
CREATE INDEX IF NOT EXISTS idx_users_email             ON users(email);
CREATE INDEX IF NOT EXISTS idx_refresh_tokens_user_id  ON refresh_tokens(user_id);
CREATE INDEX IF NOT EXISTS idx_login_audit_user_id     ON login_audit(user_id);

-- ===========================================
-- DEFAULT ADMIN USER
-- Username : admin
-- Password : Admin@123  (BCrypt hash below)
-- NOTE: Replace the hash with one generated by your own
--       BCryptPasswordEncoder before going beyond local/dev.
-- ===========================================
INSERT INTO users (username, email, password, first_name, last_name)
VALUES (
    'admin',
    'admin@finpilot.com',
    '$2a$10$GRLdNijSQMUvl/au9ofL.eDwmoohzzS7.rmRg21KiXoX1uqFxOIPi',
    'System',
    'Administrator'
)
ON CONFLICT (username) DO NOTHING;

INSERT INTO user_roles (user_id, role_id)
SELECT u.id, r.id
FROM users u, roles r
WHERE u.username = 'admin'
  AND r.role_name = 'ROLE_ADMIN'
ON CONFLICT DO NOTHING;

-- ===========================================
-- SAMPLE NORMAL USER
-- Password : User@123 (replace hash before non-local use)
-- ===========================================
INSERT INTO users (username, email, password, first_name, last_name)
VALUES (
    'saudagar',
    'saudagar.yadav@gmail.com',
    '$2a$10$GRLdNijSQMUvl/au9ofL.eDwmoohzzS7.rmRg21KiXoX1uqFxOIPi',
    'Saudagar',
    'Yadav'
)
ON CONFLICT (username) DO NOTHING;

INSERT INTO user_roles (user_id, role_id)
SELECT u.id, r.id
FROM users u, roles r
WHERE u.username = 'saudagar'
  AND r.role_name = 'ROLE_USER'
ON CONFLICT DO NOTHING;
